In [ ]:
#Inheritance
#Decorators
#Numpy

In [ ]:
#Single inheritance

In [1]:
class father:
  def flat(self):
    print("father's flat")
class son(father):
  def house(self):
    print("son's house")
s = son()
s.flat()
s.house()

father's flat
son's house


In [2]:
#Multiple inheritance
class father:
  def flat(self):
    print("father's flat")

class mother:
  def car(self):
    print("mother's car")

class son(father, mother):
  def house(self):
    print("son's house")

s = son()
s.flat()
s.house()
s.car()


father's flat
son's house
mother's car


In [3]:
# Multilevel inheritance
class Grandfather:
  def grand_property(self):
    print("Grandfather's property")

class Father(Grandfather):
  def father_property(self):
    print("Father's property")

class Son(Father):
  def son_property(self):
    print("Son's property")

s = Son()
s.grand_property()
s.father_property()
s.son_property()


Grandfather's property
Father's property
Son's property


In [4]:
#Hierarchical Inheritance
class Father:
  def flat1(self):
    print("Father's flat1")

class Son1(Father):
  def house1(self):
    print("Son's house1")

class Son2(Father):
  def house2(self):
    print("Son's house2")

s1 = Son1()
s2 = Son2()
s1.flat1()
s1.house1()
s2.flat1()
s2.house2()

Father's flat1
Son's house1
Father's flat1
Son's house2


In [ ]:
#Polymorphism

In [6]:
print(100 + 200) # "+" is working as an addition operator
print("Hello " + "World") # "+" is working as a concatenation operator
#so "+" operator is working as an polymorphism

300
Hello World


In [ ]:
#Encapsulaation

In [8]:
class Bank:
  def __init__(self, balance):
    self.__balance = balance
  def deposit(self, amount):
    self.__balance += amount
  def get_balance(self):
      return self.__balance

b = Bank(1000)
b.deposit(500)
print(b.get_balance())
print(b.__balance)

1500


AttributeError: 'Bank' object has no attribute '__balance'

In [ ]:
#Abstraction

In [10]:
from abc import ABC , abstractmethod # Abstract base class

class Paymentprocessor(ABC): # Paymentprocessor is an abstract classs because it inherits from ABC
  @abstractmethod
  def payment(self, amount):
     pass
class Creditcard(Paymentprocessor):
  def payment(self, amount):
    print(f"Credit card payment of {amount}")

class UPI(Paymentprocessor):
  def payment(self, amount):
    print(f"UPI payment of {amount}")

txn = Creditcard()
txn.payment(1000)
txn = UPI()
txn.payment(1000)


Credit card payment of 1000
UPI payment of 1000


In [ ]:
#Iterator
#An iterator is an object in python that allows sequential traversal over a collection like a list , tuple ,string , etc... , without needing an index.

In [ ]:
#Iterable vs Iterator
# Iterable - Any object that you can that you can loop (like a list or string)
# Iterator - An object with __next__() method that returns data one item at a time


In [ ]:
#Genrator
#by writing a class with the yeild keyword
#more memory-efficient by nature
#use for fast, simple sequence generation

#Numpy

In [ ]:
#Numpy
#Numpy is the backbome of ML and DS
#It is one of the most imp libraries in pyhton for numerical cumputing
#NUM- Numerical
#py- python
#numpy stores the data in an array
#An array is collection of items of same data type with conitinuos memory location
#Numpy consist of two main part
#1. ndarray - numpy array
#2. ufunc - universal functio

In [11]:
import numpy as np
print(np.__version__)

2.0.2


In [14]:
#ndarray
#Syntax
#np.array(data , dtype)
#data - A list of tuple of numbers
#dtype - Data type of the array (optional)

a = np.array([10,20,30,40,50])
print(a)
print(type(a))
print(a.dtype)

[10 20 30 40 50]
<class 'numpy.ndarray'>
int64


In [15]:

a = np.array([10,20,30.5,40,50])
print(a)
print(type(a))
print(a.dtype)

[10.  20.  30.5 40.  50. ]
<class 'numpy.ndarray'>
float64


In [20]:

a = np.array([10,20,30,40,50])
print(a)
print(type(a))
print(a.dtype)

[10 20 30 40 50]
<class 'numpy.ndarray'>
int64


In [24]:
#Basic Functions of Numpy
print(np.sum(a)) #sum of all elements
print(np.min(a)) #min of all elements
print(np.max(a)) #max of all elements
print(np.mean(a)) #mean of all elements
print(np.median(a)) #median of all elements
print(np.std(a)) #standard deviation of all elements
print(np.var(a)) #variance of all elements
print(np.sort(a)) #sorting of all elements
print(np.argsort(a)) #sorting of all elements
print(np.argmin(a)) #sorting of all elements
print(np.argmax(a)) #sorting of all elements
print(np.unique(a)) #sorting of all elements


150
10
50
30.0
30.0
14.142135623730951
200.0
[10 20 30 40 50]
[0 1 2 3 4]
0
4
[10 20 30 40 50]


In [28]:
#Indexing and slicing in a Numpy array is exactly same as in list
print(a[1])  #first element
print(a[0:3]) #first three elements
print(a[-1]) #last element
print(a[-3:]) #last three elements


20
[10 20 30]
50
[30 40 50]


In [31]:
a = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))
print(np.sort(a))
print(np.argsort(a))
print(np.argmin(a))
print(np.argmax(a))
print(np.unique(a))


450
10
90
50.0
50.0
25.81988897471611
666.6666666666666
[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[0 1 2]
 [0 1 2]
 [0 1 2]]
0
8
[10 20 30 40 50 60 70 80 90]


In [32]:
np.linalg.det(a) #Determinant fo matrix a

np.float64(-4.263256414560599e-12)

In [34]:
np.linspace(0, 10 ,5) # it will create an array of 5 elements btw 0 and 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [35]:
print(np.zeros((3,4))) # 3rows and 4 columns

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [36]:
print(np.zeros(6))

[0. 0. 0. 0. 0. 0.]


In [41]:
#Syntax
#np.ones(shape, dtype)
print(np.ones((3,4,)))
#we only have zeros and ones this is bcuz image creation this zeros and ones is used in image

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [38]:
np.identity(5, dtype="int") #idnetity matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [46]:
# random submodules
#funtions and its uses one by one
#1. np.random.rnd()
#Generates random numbers in the range of [0.0, 1.0]
z= print(np.random.rand(3,4))


[[0.62520034 0.8239961  0.92268635 0.44584731]
 [0.95908237 0.01524664 0.96599544 0.21333445]
 [0.11818564 0.38645675 0.02062966 0.50947434]]


In [47]:
for i in range(5):
  print(i)

0
1
2
3
4


In [48]:
np.arange(5)  # it store the range in numpy array.

array([0, 1, 2, 3, 4])

In [49]:
np.arange(12).reshape(3,4) # this is only work when the multiplication of row and column is equal to the number of elment in array


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
# speed of numpy and list
# numpy is faster than list because it uses contiguous memory allocation

l1 = range(1000000)
l2 = range(1000000)
a1 = np.arange(1000000)
a2 = np.arange(1000000)

#list
import time
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
end = time.time()
print("Time taken by list: ", (end-start)*1000)

#numpy
start = time.time()
result = a1 + a2
end = time.time()
print("Time taken by numpy: ", (end-start)*1000)

Time taken by list:  138.71479034423828
Time taken by numpy:  5.859851837158203
